# yaml-language-server: $schema=https://raw.githubusercontent.com/woodpecker-ci/woodpecker/main/pipeline/frontend/yaml/linter/schema/schema.json

steps:
  - commands:
      - pip install --root-user-action=ignore --cache-dir=/cache/pip --progress-bar=off "meson==$MESON_VERSION"
      - meson format -qr
    environment:
      # renovate: datasource=pypi depName=meson versioning=pep440
      MESON_VERSION: 1.5.2
    image: docker.io/library/python:3.13.0-bookworm@sha256:c8ab6e77bd9788bd7952069fc8d19e5f5c6954712f1e9a0739882963dca9438c
    name: chech-meson-format
    volumes:
      - wp-cache_global_pip:/cache/pip

when:
  - event: pull_request
