# yaml-language-server: $schema=https://raw.githubusercontent.com/woodpecker-ci/woodpecker/main/pipeline/frontend/yaml/linter/schema/schema.json

steps:
  - commands:
      - pip install --root-user-action=ignore --cache-dir=/cache/pip --progress-bar=off "cpplint==$CPPLINT_VERSION"
      - |
        git ls-tree --name-only -r HEAD | grep -E "^(.+\/)?.*[^\/\s]\.(c|h)$" | while read f ; do
          echo "checking $f" && cpplint "$f"
        done
    environment:
      # renovate: datasource=pypi depName=cpplint versioning=pep440
      CPPLINT_VERSION: 2.0.0
    image: docker.io/library/python:3.13.0-bookworm@sha256:d6038cd5fe90d591c8a7589330b003fc0ae7ac2958d4b9e1b90e0f88515154b5
    name: check-cpplint
    volumes:
      - wp-cache_global_pip:/cache/pip

when:
  - event: pull_request
