# yaml-language-server: $schema=https://raw.githubusercontent.com/woodpecker-ci/woodpecker/main/pipeline/frontend/yaml/linter/schema/schema.json

steps:
  - commands:
      # Configure apt.
      - rm /etc/apt/apt.conf.d/70debconf /etc/apt/apt.conf.d/docker-autoremove-suggests /etc/apt/apt.conf.d/docker-clean /etc/apt/apt.conf.d/docker-gzip-indexes
      - echo 'APT::Get::Install-Recommends "false";\nAPT::Get::Install-Suggests "false";' | tee /etc/apt/apt.conf.d/01-ci-no-extra-pkgs

      # Install clang, ninja and libc6-dbg.
      - echo "deb https://apt.llvm.org/bookworm llvm-toolchain-bookworm-18 main" | tee /etc/apt/sources.list.d/llvm.list
      - curl "https://apt.llvm.org/llvm-snapshot.gpg.key" -o /etc/apt/trusted.gpg.d/apt.llvm.org.asc
      - apt-get update
      - apt-get install -y --no-install-recommends clang-18 ninja-build libc6-dbg

      # Install meson.
      - pip install --root-user-action=ignore --cache-dir=/cache/pip --progress-bar=off "meson==$MESON_VERSION"

      # Install valgrind.
      - cd /cache/valgrind
      - |
        if [ ! -d "valgrind-$VALGRIND_VERSION" ]; then
          curl -sO "https://sourceware.org/pub/valgrind/valgrind-$VALGRIND_VERSION.tar.bz2"
          bzip2 --decompress --force "valgrind-$VALGRIND_VERSION.tar.bz2"
          tar -xf "valgrind-$VALGRIND_VERSION.tar"
        fi
      - cd "valgrind-$VALGRIND_VERSION"
      - ./configure
      - make -j "$(nproc)"
      - make install
      # Required by valgrind when running inside docker container.
      - ulimit -n 4096
      - cd $CI_WORKSPACE

      # Setup and test.
      - meson setup --reconfigure /cache/build || meson setup /cache/build
      - meson test --wrap='valgrind --leak-check=full --error-exitcode=1' -C /cache/build
    environment:
      CC: clang-18
      CXX: clang++-18
      DEBIAN_FRONTEND: noninteractive
      # renovate: datasource=pypi depName=meson versioning=pep440
      MESON_VERSION: 1.5.2
      VALGRIND_VERSION: 3.23.0
    image: docker.io/library/python:3.13.0-bookworm@sha256:0eb8d3feda44654b7bc3e6e21dd19b793ce9eda75bbd0cf16a2407a1f0a4448b
    name: check-meson-test
    volumes:
      - wp-cache_${CI_REPO_REMOTE_ID}_build:/cache/build
      - wp-cache_${CI_REPO_REMOTE_ID}_valgrind-build:/cache/valgrind
      - wp-cache_global_apt-cache:/var/cache/apt
      - wp-cache_global_apt-lists:/var/lib/apt/lists
      - wp-cache_global_pip:/cache/pip

when:
  - event: pull_request
