# yaml-language-server: $schema=https://raw.githubusercontent.com/woodpecker-ci/woodpecker/main/pipeline/frontend/yaml/linter/schema/schema.json

steps:
  - commands:
      - echo "deb https://apt.llvm.org/bookworm llvm-toolchain-bookworm-$CLANG_VERSION main" | tee /etc/apt/sources.list.d/llvm.list
      - curl "https://apt.llvm.org/llvm-snapshot.gpg.key" | tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc
      - apt-get update
      - apt-get install -y --no-install-recommends "clang-$CLANG_VERSION" ninja-build
      - pip install --root-user-action ignore "meson==$MESON_VERSION"
      - export CC="clang-$CLANG_VERSION"
      - export CXX="clang++-$CLANG_VERSION"
      - meson setup .build
      - meson test -C .build
    environment:
      CLANG_VERSION: 18
      # renovate: datasource=pypi depName=meson versioning=pep440
      MESON_VERSION: 1.5.2
    image: docker.io/library/python:3.13.0-bookworm@sha256:9f9fbb053718aa5cb814ba6416289a86d5d1436ddd64c0d3754d225dda5dcfbb
    name: test

when:
  - event: pull_request
