jobs:
  fmt-clang-format:
    container: docker.io/library/debian:bookworm
    env:
      CLANG_VERSION: 18
      CC: clang-18
      CXX: clang++-18
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - run: apt-get update
      - run: apt-get install -y --no-install-recommends curl ca-certificates
      - run: echo "deb http://apt.llvm.org/bookworm/ llvm-toolchain-bookworm-$CLANG_VERSION main" | tee /etc/apt/sources.list.d/llvm.list
      - run: curl "https://apt.llvm.org/llvm-snapshot.gpg.key" | tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc
      - run: apt-get update
      - run: apt-get install -y --no-install-recommends "clang-format-$CLANG_VERSION" python3 python3-pip ninja-build
      - run: pip install --no-cache-dir --break-system-packages --compile meson
      - run: meson setup --reconfigure .build || rm -rf .build && meson setup .build
      - run: ninja -C .build clang-format
      - uses: stefanzweifel/git-auto-commit-action@8621497c8c39c72f3e2a999a26b4ca1b5058a842 # v5.0.1
        with:
          commit_message: "chore: format files"

name: fmt-clang-format

"on":
  pull_request:
    branches:
      - main
