jobs:
  lint-c:
    env:
      CC: clang
      CXX: clang++
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - run: sudo apt-get update
      - run: sudo apt-get install -y --no-install-recommends meson clang-tidy
      - run: meson setup --reconfigure .build || rm -rf .build && meson setup .build
      - run: ninja -C .build clang-tidy

name: lint-c

"on":
  pull_request:
    branches:
      - main
