jobs:
  lint-c:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - run: apt-get update
      - run: apt-get install -y --no-install-recommends meson clang-tidy
      - run: meson setup .build
      - run: ninja -C .build clang-tidy

name: lint-c

"on":
  pull_request:
    branches:
      - main
