jobs:
  test-c:
    env:
      CC: clang
      CXX: clang++
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - run: sudo apt-get update
      - run: sudo apt-get install -y --no-install-recommends meson clang
      - uses: actions/cache@2cdf405574d6ef1f33a1d12acccd3ae82f47b3f2 # v4.1.0
        with:
          key: ${{ runner.os }}
          path: .build
      - run: meson setup --reconfigure .build || rm -rf .build && meson setup .build
      - run: meson test -C .build

name: test-c

"on":
  pull_request:
    branches:
      - main
