jobs:
  test-c:
    container: docker.io/library/debian:bookworm
    env:
      CLANG_VERSION: 18
      CC: clang-18
      CXX: clang++-18
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - run: apt-get update
      - run: apt-get install -y --no-install-recommends curl ca-certificates
      - run: echo "deb http://apt.llvm.org/bookworm/ llvm-toolchain-bookworm-$CLANG_VERSION main" | tee /etc/apt/sources.list.d/llvm.list
      - run: curl "https://apt.llvm.org/llvm-snapshot.gpg.key" | tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc
      - run: apt-get update
      - run: apt-get install -y --no-install-recommends "clang-$CLANG_VERSION" python3 python3-pip ninja-build
      - run: pip install --no-cache-dir --break-system-packages --compile meson
      - uses: actions/cache@2cdf405574d6ef1f33a1d12acccd3ae82f47b3f2 # v4.1.0
        with:
          key: ${{ runner.os }}
          path: .build
      - run: meson setup --reconfigure .build || rm -rf .build && meson setup .build
      - run: meson test -C .build

name: test-c

"on":
  pull_request:
    branches:
      - main
